# An example PyTorch environment for LUMI
name: pytorch_example
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - lightning>=2.5.1
  - pip:
    # The PyTorch ROCm version here should match the ROCm version of the base image you chose
    - --extra-index-url https://download.pytorch.org/whl/rocm6.2.4
    - torch==2.6.0+rocm6.2.4
    - torchvision==0.21.0+rocm6.2.4